### ISSUE TITLE
"stop_if_emergency" modifier does nothing

### ISSUE THREAD

**Issue by TripleSpeeder** [robertsimoes/Solidity-Contract-Patterns#1]
Either the modifier body is missing or I am completely missing the point right now :)

https://github.com/robertsimoes/Solidity-Contract-Patterns/blob/34bd92f5481669358872c2c676cc8d025010c8b8/CircuitBreaker/CircuitBreaker.sol#L16

**Comment by aquaflamingo** [comment]
Thanks @TripleSpeeder, a kind fellow just fixed this mistake, closing.
